version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - '27019:27017'
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: nestjs_db
    volumes:
      - ./mongodb:/data/db